config/routes.rb
GOT::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_session
  end

  get '/registration', :to => "users#registration", :as => :new_user_registration
  get '/login', :to => "users#login"
  get '/airsoft', :to => "home#airsoft"
  get '/rules', :to => "home#rules"

  get 'game_calendars', :to => "game_calendars#index"
  get 'game_calendars/:id', :to => "game_calendars#show", :as => :game_calendar

  get 'camps', :to => "camps#index"

  namespace :admin do
    resources "pages"
    resources "roles"
    resources "users"
    resources "game_calendars"
    resources "camps"
  end

  root :to => "home#index"

end

app/views/admin/pages/_form.html.erb
<%= form_for(@page, :class=>"form") do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br />
    <%= f.text_area :content, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :slug %><br />
    <%= f.text_field :slug, :class=>'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/admin/pages/index.html.erb
<h1>Listing pages</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Slug</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.slug %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to 'New Page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<div class="page-header"><h1>New page</h1></div>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @page.title %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>

<p>
  <b>Slug:</b>
  <%= @page.slug %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>