config/routes.rb
GOT::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_session
  end

  get '/registration', :to => "users#registration", :as => :new_user_registration
  get '/login', :to => "users#login"
  get '/airsoft', :to => "home#airsoft"
  get '/rules', :to => "home#rules"

  get 'game_calendars', :to => "game_calendars#index"
  get 'game_calendars/:id', :to => "game_calendars#show", :as => :game_calendar

  get 'camps', :to => "camps#index"

  namespace :admin do
    resources "pages"
    resources "roles"
    resources "users"
    resources "game_calendars"
    resources "camps"
  end

  root :to => "home#index"

end

app/models/game_calendar.rb
# -*- encoding : utf-8 -*-
class GameCalendar < ActiveRecord::Base
  attr_accessible :date, :instructions, :location, :map, :provider, :title

  validates_presence_of :instructions, :location, :title
end

app/controllers/admin/game_calendars_controller.rb
# -*- encoding : utf-8 -*-
class Admin::GameCalendarsController < Admin::AdminController
  # GET /admin/game_calendars
  # GET /admin/game_calendars.json
  def index
    @game_calendars = GameCalendar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @game_calendars }
    end
  end

  # GET /admin/game_calendars/new
  # GET /admin/game_calendars/new.json
  def new
    @game_calendar = GameCalendar.new

    respond_to do |format|
      format.html { render "edit" } # edit.html.erb
      format.json { render json: @game_calendar }
    end
  end

  # GET /admin/game_calendars/1/edit
  def edit
    @game_calendar = GameCalendar.find(params[:id])
  end

  # POST /admin/game_calendars
  # POST /admin/game_calendars.json
  def create
    @game_calendars = GameCalendar.new(params[:game_calendar])

    respond_to do |format|
      if @game_calendars.save
        format.html { redirect_to admin_game_calendars_path, notice: 'Game calendar was successfully created.' }
        format.json { render json: @game_calendars, status: :created, location: @game_calendars }
      else
        format.html { render action: "new" }
        format.json { render json: @game_calendars.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/game_calendars/1
  # PUT /admin/game_calendars/1.json
  def update
    @game_calendars = GameCalendar.find(params[:id])

    respond_to do |format|
      if @game_calendars.update_attributes(params[:game_calendar])
        format.html { redirect_to admin_game_calendars_path, notice: 'Game calendar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game_calendars.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/game_calendars/1
  # DELETE /admin/game_calendars/1.json
  def destroy
    @game_calendars = GameCalendar.find(params[:id])
    @game_calendars.destroy

    respond_to do |format|
      format.html { redirect_to admin_game_calendars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/game_calendars_controller.rb
# -*- encoding : utf-8 -*-
class GameCalendarsController < ApplicationController
  def index
    @game_calendars = GameCalendar.where("date > ?", Date.current - 1.years)
  end

  def show
    @game_calendar = GameCalendar.find(params[:id])
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
  end
end

app/helpers/admin/game_calendars_helper.rb
# -*- encoding : utf-8 -*-
module Admin::GameCalendarsHelper
end

app/views/admin/game_calendars/_form.html.erb
<%= form_for(@game_calendar, :url => "/admin/game_calendars/" + @game_calendar.id.to_s) do |f| %>
    <% if @game_calendar.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@game_calendar.errors.count, "error") %> prohibited this game_calendar from being
                saved:</h2>

            <ul>
                <% @game_calendar.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <div class="form-group">
        <%= f.label :date, "Quando" %><br/>
        <%= f.datetime_select :date, :class => "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :location, "CT / Local" %><br/>
        <%= f.text_field :location, :class => "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :map, "Google Maps" %><br/>
        <%= f.text_field :map, :class => "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :title, "Nome do Jogo" %><br/>
        <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :provider, "Organizador" %><br/>
        <%= f.text_field :provider, :class => "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :instructions, "Instruções" %><br/>
        <%= f.text_area :instructions, :class => "form-control markitup" %>
    </div>
    <div class="form-group">
        <%= f.submit "Adicionar Jogo", :class=>"btn btn-primary" %>
    </div>
<% end %>

app/views/admin/game_calendars/edit.html.erb
<div class="page-header"><h1>New Jogo</h1></div>

<%= render 'form' %>

<%= link_to 'Back', game_calendars_path %>

app/views/admin/game_calendars/index.html.erb
<div class="page-header"><h1>Jogos</h1></div>

<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th>Quando</th>
        <th>Onde</th>
        <th>Quem</th>
        <th>O Que</th>
        <th></th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <% @game_calendars.each do |game_calendar| %>
        <tr>
            <td><%= game_calendar.date %></td>
            <td><%= game_calendar.location %></td>
            <td><%= game_calendar.provider %></td>
            <td><%= game_calendar.title %></td>
            <td><%= link_to 'Editar', edit_admin_game_calendar_path(game_calendar) %></td>
            <td><%= link_to 'Apagar', admin_game_calendar_path(game_calendar), confirm: 'Certeza?', method: :delete %></td>
        </tr>
    <% end %>
    </tbody>
</table>
<%= link_to 'Novo Jogo', new_admin_game_calendar_path %>

app/views/admin/game_calendars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @game_calendar.date %>
</p>

<p>
  <b>Location:</b>
  <%= @game_calendar.location %>
</p>

<p>
  <b>Map:</b>
  <%= @game_calendar.map %>
</p>

<p>
  <b>Instructions:</b>
  <%= @game_calendar.instructions %>
</p>

<p>
  <b>Title:</b>
  <%= @game_calendar.title %>
</p>

<p>
  <b>Provider:</b>
  <%= @game_calendar.provider %>
</p>


<%= link_to 'Edit', edit_game_calendar_path(@game_calendar) %> |
<%= link_to 'Back', game_calendars_path %>