config/routes.rb
GOT::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_session
  end

  get '/registration', :to => "users#registration", :as => :new_user_registration
  get '/login', :to => "users#login"
  get '/airsoft', :to => "home#airsoft"
  get '/rules', :to => "home#rules"

  get 'game_calendars', :to => "game_calendars#index"
  get 'game_calendars/:id', :to => "game_calendars#show", :as => :game_calendar

  get 'camps', :to => "camps#index"

  namespace :admin do
    resources "pages"
    resources "roles"
    resources "users"
    resources "game_calendars"
    resources "camps"
  end

  root :to => "home#index"

end

app/models/role.rb
# -*- encoding : utf-8 -*-
class Role < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :users
end

app/controllers/admin/roles_controller.rb
# -*- encoding : utf-8 -*-
class Admin::RolesController < Admin::AdminController
  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.json
  def new
    @role = Role.new

    respond_to do |format|
      format.html # edit.html.erb
      format.json { render json: @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to admin_role_path(@role), notice: 'Role was successfully created.' }
        format.json { render json: admin_role_path(@role), status: :created, location: @role }
      else
        format.html { render action: "new" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.json
  def update
    @role = Role.find(params[:id])

    respond_to do |format|
      if @role.update_attributes(params[:role])
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role = Role.find(params[:id])
    @role.destroy

    respond_to do |format|
      format.html { redirect_to roles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/roles_helper.rb
# -*- encoding : utf-8 -*-
module RolesHelper
end

app/views/admin/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_roles_path(@role) %> |
<%= link_to 'Back', admin_roles_path %>

app/views/admin/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roles.each do |role| %>
  <tr>
    <td><%= role.name %></td>
    <td><%= link_to 'Show', admin_role_path(role) %></td>
    <td><%= link_to 'Edit', edit_admin_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Role', new_admin_role_path %>

app/views/admin/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_roles_path %>

app/views/admin/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @role.name %>
</p>

<%= link_to 'Edit', edit_admin_role_path(@role) %> |
<%= link_to 'Back', admin_roles_path %>