config/routes.rb
GOT::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_session
  end

  get '/registration', :to => "users#registration", :as => :new_user_registration
  get '/login', :to => "users#login"
  get '/airsoft', :to => "home#airsoft"
  get '/rules', :to => "home#rules"

  get 'game_calendars', :to => "game_calendars#index"
  get 'game_calendars/:id', :to => "game_calendars#show", :as => :game_calendar

  get 'camps', :to => "camps#index"

  namespace :admin do
    resources "pages"
    resources "roles"
    resources "users"
    resources "game_calendars"
    resources "camps"
  end

  root :to => "home#index"

end

app/views/layouts/_menu.html.erb
<%
   fixed_class = 'navbar-fixed-top' unless controller.controller_name == 'home' && controller.action_name == 'index'
%>

<nav class="navbar navbar-inverse <%= fixed_class %>" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to "G.O.T. Airsoft Team", "/", :class => "navbar-brand" %>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li><%= link_to "Airsoft", airsoft_path %></li>
                <li><%= link_to "Regras", rules_path %></li>
                <li><%= link_to "Campos", camps_path %></li>
                <% if can? :read, GameCalendar %>
                    <li><%= link_to "Jogos", game_calendars_path %></li>
                <% end %>
            </ul>
            <form class="navbar-form navbar-left" role="search">

            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <% unless user_session %>
                        <%= link_to "Entrar", login_path %>
                    <% else %>
                        <%= link_to "Sair", destroy_session_path %>
                    <% end %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>GOT</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/menu' %>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <%= yield %>
        </div>
    </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>GOT</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
</head>
<body>

    <%= render 'layouts/menu' %>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <%= yield %>
        </div>
    </div>
</div>

</body>
</html>